Removed lwip
hermit-os/newlib pull request #1
Opened 2024-05-29 07:08 UTC by CarlWachter

Removed lwip and replaced all references with interfaces to hermit networking.

Should be merged with hermit-os/hermit-playground#27 to avoid breaking hermit-os/hermit-gcc, as it only pulls the latest commits.

2024-05-29 13:37 UTC, mkroening requested changes
Thanks! Where do `inet_*.c` and friends come from?

2024-05-29 13:37 UTC, mkroening commented on newlib/libc/sys/hermit/include/sys/socket.h
> +#define sys_recvfrom          recvfrom */
```suggestion
```

2024-05-29 13:37 UTC, mkroening commented on newlib/libc/sys/hermit/include/sys/socket.h
> +//#define closesocket(s)                            sys_close(s)
```suggestion
```

Is there some specific reason for these comments?

2024-05-29 13:37 UTC, mkroening commented on newlib/libc/sys/hermit/Makefile.am
> +lib_a_SOURCES = chown.c clock_getres.c clock_gettime.c clock_nanosleep.c clock_settime.c close.c environ.c errno.c execve.c _exit.c fork.c fstat.c getpagesize.c getpid.c gettod.c isatty.c kill.c link
`inet_pton.c` seems missing.

2024-05-30 12:32 UTC, CarlWachter commented
> Thanks! Where do `inet_*.c` and friends come from?

It's from the debian source code. Ex.:
https://sources.debian.org/data/main/g/glibc/2.28-10/inet/inet_ntoa.c

2024-05-31 12:57 UTC, mkroening requested changes
> > Thanks! Where do `inet_*.c` and friends come from?
> 
> It's from the debian source code. Ex.: https://sources.debian.org/data/main/g/glibc/2.28-10/inet/inet_ntoa.c

Do we actually need any new files besides `inet_ntoa.c`? `Makefile.in` does not have other new files.

Instead of taking them from glibc, can we just use [`newlib/libc/sys/linux/net/inet_ntoa.c`](https://github.com/hermit-os/newlib/blob/7db17585c746d59b539df6fef738b22573d0636b/newlib/libc/sys/linux/net/inet_ntoa.c)?

If we really need to add new files from glibc, please add a [SPDX License ID](https://spdx.dev/learn/handling-license-info/) and add a link to the source. For example:

```c
/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* From https://sourceware.org/git/?p=glibc.git;a=blob;f=inet/inet_ntoa.c;h=341d8591c30b88d4415898d93ae0dcbd7bf4e3d6;hb=46b5e98ef6f1b9f4b53851f152ecb8209064b26c */
```

2024-05-31 12:57 UTC, mkroening commented on newlib/libc/sys/hermit/Makefile.in
This file is out of date and needs to be regenerated with automake.

2024-05-31 14:52 UTC, CarlWachter commented
> Do we actually need any new files besides `inet_ntoa.c`? `Makefile.in` does not have other new files.

True, i removed the others. If they are needed in the future, they are easy to add back in.

> Instead of taking them from glibc, can we just use [`newlib/libc/sys/linux/net/inet_ntoa.c`](https://github.com/hermit-os/newlib/blob/7db17585c746d59b539df6fef738b22573d0636b/newlib/libc/sys/linux/net/inet_ntoa.c)?

I tried that and it led to a lot of issues, since one linux file typically seeks to have 20 other linux files included with it.

> If we really need to add new files from glibc, please add a [SPDX License ID](https://spdx.dev/learn/handling-license-info/) and add a link to the source. For example:
> 
> ```c
> /* SPDX-License-Identifier: LGPL-2.1-or-later */
> /* From https://sourceware.org/git/?p=glibc.git;a=blob;f=inet/inet_ntoa.c;h=341d8591c30b88d4415898d93ae0dcbd7bf4e3d6;hb=46b5e98ef6f1b9f4b53851f152ecb8209064b26c */
> ```
Done

2024-05-31 14:52 UTC, CarlWachter commented on newlib/libc/sys/hermit/Makefile.in
Resolved, by changing Makefile.am back to same version as Makefile.in

2024-06-03 10:14 UTC, mkroening approved these changes

2024-06-04 10:16 UTC, merged